services:
  db:
    image: 'postgres:16'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crisisrelief
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - '5001:5001'
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: sh -c "npm --prefix src/Database run migrate && node dist/src/server.js"


  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        VITE_API_URL: http://localhost:5001
    ports:
      - '5173:80'
    env_file:
      - ./frontend/.env

volumes:
  pgdata:
