/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Numeric = ColumnType<string, number | string, number | string>;

export type Resourcestatuses = "Closed" | "Full" | "Open" | "Unknown";

export type Resourcetypes = "FoodBank" | "MedicalCenter" | "MentalHealthSupport" | "Shelter" | "SupplyStation";

export interface Resources {
  address: string | null;
  city: string | null;
  latitude: Numeric | null;
  longitude: Numeric | null;
  name: string | null;
  openHours: string | null;
  resourceId: string | null;
  state: string | null;
  status: Resourcestatuses | null;
  type: Resourcetypes | null;
  zipCode: string | null;
}

export interface DB {
  resources: Resources;
}
